### ISSUE TITLE
why no source though

### ISSUE THREAD

**Issue by blubbll** [Matriz88/CubeWorldServerRunner#1]
or at least show more info like programming language, what it do or something.
this is github and not sourceforge lol

**Comment by Matriz88** [comment]
hi @blubbll 
you're totally right, initially I made the source repository private and worked on this just for fun. When I decided to share the tool I thought made sense to give people with no dev skills the possibility to download just the executable.

I made it public and linked it in the readme :) Anyways I prefer to keep the two repositories separated so that people can download it from here without any additional source code file.
